-- CREATE TABLE 테이블명(컬럼명 타입(길이));
CREATE TABLE TBM_MEMBER (
	NAME VARCHAR2(100),
	AGE NUMBER
);
-- 주의점
-- 컬럼이 여러개 일 때 , 잘 써야 함
-- 위아래 공백 두지 않기
-- 같은 이름으로는 안 만들어짐
-- 마지막에는 콤마 안붙힘

CREATE TABLE TBL_MEMBER(
	ID NUMBER, -- 차량 식별 번호
	BRAND VARCHAR2(100), -- 브랜드
	COLOR VARCHAR2(100), -- 색깔
	PRICE NUMBER, -- 가격
	CONSTRAINT CAR_PK PRIMARY KEY(ID) -- 테이블을 생성하면서 제약조건을 지정
);

-- 영구삭제이기 때문에 조심해야한다.
DROP TABLE TBL_MEMBER;
DROP TABLE TBM_MEMBER;

CREATE TABLE ex02_10(
Col1 VARCHAR2(10) NOT NULL,
Col2 VARCHAR2(10),
Create_date DATE DEFAULT SYSDATE
);
-- 컬럼명 변경
-- ALTER TABLE 테이블명 RENAME COLUMN 기존컬럼명 TO 새로운컬럼명;
ALTER TABLE ex02_10 RENAME COLUMN Col1 TO Col11;

-- 컬럼타입 변경
-- ALTER TABLE 테이블명 MODIFY 컬럼명 데이터타입;
ALTER TABLE EX02_10 MODIFY Col2 VARCHAR2(30);

-- 컬럼삭제
-- ALTER TABLE 테이블명 DROP COLUMN 컬럼명;
ALTER TABLE EX02_10 DROP COLUMN Create_date;

-- 컬럼추가
-- ALTER TABLE 테이블명 ADD 컬럼명 컬럼타입;
ALTER TABLE EX02_10 ADD Col3 NUMBER;

-- 제약조건 추가
-- 테이블이 생성된 후 제약조건을 추가 or 삭제
-- alter table 테이블명 add constraint 제약조건명 제약조건종류(컬럼명);
ALTER TABLE EX02_10 ADD CONSTRAINT pk_ex2_10 PRIMARY KEY(Col11); 

-- 제약조건 삭제
-- ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
ALTER TABLE EX02_10 DROP CONSTRAINT pk_ex2_10;

CREATE TABLE TBL_ANIMAL(
ID NUMBER PRIMARY key,
"TYPE" VARCHAR2(100),
AGE NUMBER(3),
FEED VARCHAR2(100)
);
-- 제약조건 삭제하기
ALTER TABLE TBL_ANIMAL DROP CONSTRAINT SYS_C007001;

-- 제약조건 추가하기
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT ANIMAL_PK PRIMARY KEY(ID);

-- TBL_ANIMAL 테이블 삭제하기
DROP TABLE TBL_ANIMAL ;

-- DEFAULT 와 CHECK 제약조건
CREATE TABLE TBL_STUDENT (
	ID NUMBER, -- 학번
	NAME VARCHAR2(100), -- 이름
	MAJOR VARCHAR2(100), -- 전공
	GENDER CHAR(1) DEFAULT 'W' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER = 'M' OR GENDER = 'W'),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK (BIRTH >= TO_DATE('1980-01-01','YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);